apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd
    repoURL: 'https://github.com/aslanpour/aiFaaS'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      #apply file deletion from repo to kubernetes
      prune: true
      #undo manual changes made by kubectl
      selfHeal: true
    syncOptions:
      - CreateNamespace=true