apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd
    repoURL: 'https://github.com/aslanpour/aiFaaS'
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: aifaas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true