apiVersion: apps/v1
kind: Deployment
metadata:
  name: aifaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aifaas
  template:
    metadata:
      labels:
        app: aifaas
    spec:
      containers:
      - name: aifaas 
        image: ghcr.io/aslanpour/my-app:91f8034b7cc082ee2675911d56fa3d8c71c3b202
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: MODEL_PRE_LOAD
          value: "cpu-only"
      nodeName: "master"