apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssd-cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssd-cpu
  template:
    metadata:
      labels:
        app: ssd-cpu
    spec:  
      nodeName: "cpu-node"      
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_IPS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIPs
        - name: POD_HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        image: aslanpour/ssd:cpu-tpu
        name: ssd-cpu
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /dev/bus/usb
          name: usb-devices
      volumes:
      - hostPath:
          path: /dev/bus/usb
          type: ""
        name: usb-devices

---
apiVersion: v1
kind: Service
metadata:
  name: ssd-cpu
spec:
  selector:
    app: ssd-cpu
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080