apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: ssd-cpu-function
  namespace: openfaas-fn
spec:
  image: aslanpour/ssd:cpu-tpu
  labels:
    com.openfaas.scale.max: "1"
    com.openfaas.scale.min: "1"
  name: ssd-cpu-function
  constraints:
  - "kubernetes.io/hostname=cpu-node"

