apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssd-tpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssd-tpu
  template:
    metadata:
      labels:
        app: ssd-tpu
    spec:
      nodeName: "tpu-node"
      containers:
      - env:
        - name: MODEL_PRE_LOAD
          value: "yes"
        - name: MODEL_RUN_ON
          value: tpu
        - name: WAITRESS_THREADS
          value: "1"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_IPS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIPs
        - name: POD_HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        image: aslanpour/ssd:cpu-tpu
        name: ssd-tpu
        ports:
        - containerPort: 8080
          protocol: TCP
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/bus/usb
          name: usb-devices
      volumes:
      - hostPath:
          path: /dev/bus/usb
          type: ""
        name: usb-devices
---
apiVersion: v1
kind: Service
metadata:
  name: ssd-tpu
spec:
  selector:
    app: ssd-tpu
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080