apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: ssd-gpu-function
  namespace: openfaas-fn
spec:
  image: aslanpour/ssd:cpu-tpu-gpu
  labels:
    com.openfaas.scale.max: "1"
    com.openfaas.scale.min: "1"
