name: ArgoCD

on:
  workflow_run:
    workflows: ["Build Multi-arch Containers and Push"]
    types: [completed]

jobs:
    update-argocd-deployment:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Creat image name
          run: |
            REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            echo "::set-env name=REPO_NAME::$REPO_NAME"
          shell: bash
        - name: Replace image value in ArgoCD
          run: |
            echo "REPO_NAME=$REPO_NAME"
            echo "REPO_NAME=${{ REPO_NAME }}"
            sed -i 's|image:.*|image: ghcr.io/${{ REPO_NAME }}:${{ vars.IMAGE_TAG }}|' argocd/deployment.yml
        - name: Commit and push changes
          run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git status
            git add argocd/deployment.yml
            git commit -m "Update image reference for ArgoCD"
            git push
    on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
          - run: echo 'The triggering workflow failed'