name: Build Multi-arch Containers and Push

on:
  workflow_run:
    workflows: ["Test"]
    types: [completed]

jobs:
  build_push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            aslanpour/aifaas:${{ vars.IMAGE_TAG }}
            ghcr.io/aslanpour/aifaas:${{ vars.IMAGE_TAG }}
      # - name: Push Docker image to DockerHub - Login to Docker Hub
      #   if: success() 
      #   run: |
      #     echo ${{ secrets.DOCKERHUB_PAT }} | docker login --username ${{ vars.DOCKERHUB_USERNAME }} --password-stdin  
      # - name: Push Docker Image to Docker Hub - Push
      #   if: success()
      #   run: |
      #     echo "DOCKER_IMAGE_NAME= $DOCKER_IMAGE_NAME"
      #     # docker push $DOCKER_IMAGE_NAME

      # - name: Push to Github Registry - Login
      #   run: |
      #     echo ${{ github.token }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      
      # - name: Push to GitHub Registry - Rename
      #   run: |
      #     docker tag $DOCKER_IMAGE_NAME ghcr.io/$DOCKER_IMAGE_NAME
      # - name: Push to Github Registry - Push
      #   run: |
      #     #docker push ghcr.io/$DOCKER_IMAGE_NAME
      #     echo "ignore push to github"
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'